version: "3.7"
services:
  app:
    build:
      args:
        user: sample
        uid: 1000
      context: ./
      dockerfile: Dockerfile-prod
    image: laravel-startup-sample
    container_name: laravel-startup-sample-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-startup-sample

  mysql:
    image: mysql:5.7
    container_name: laravel-startup-sample-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel-startup-sample

  nginx:
    image: nginx:alpine
    container_name: laravel-startup-sample-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-startup-sample

networks:
  laravel-startup-sample:
    driver: bridge
